DROP TABLE IF EXISTS players;
DROP TABLE IF EXISTS teams;

CREATE TABLE teams (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(120) NOT NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE players (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    team_id INT UNSIGNED NOT NULL,
    name VARCHAR(150) NOT NULL,
    slug VARCHAR(200) NOT NULL,
    position VARCHAR(100) NOT NULL,
    jersey_number VARCHAR(10) NOT NULL,
    birth_date DATE NOT NULL,
    height SMALLINT NULL,
    weight SMALLINT NULL,
    birth_place VARCHAR(120) NOT NULL,
    gender CHAR(1) NOT NULL,
    nisn VARCHAR(10) NULL,
    nik VARCHAR(16) NOT NULL,
    sport_type VARCHAR(120) NOT NULL,
    email VARCHAR(190) NULL,
    phone VARCHAR(30) NULL,
    nationality VARCHAR(80) NOT NULL DEFAULT 'Indonesia',
    street VARCHAR(255) NULL,
    city VARCHAR(120) NULL,
    province VARCHAR(120) NULL,
    postal_code VARCHAR(20) NULL,
    country VARCHAR(80) NOT NULL DEFAULT 'Indonesia',
    dominant_foot VARCHAR(30) NOT NULL,
    position_detail VARCHAR(100) NOT NULL,
    dribbling TINYINT UNSIGNED NOT NULL DEFAULT 5,
    technique TINYINT UNSIGNED NOT NULL DEFAULT 5,
    speed TINYINT UNSIGNED NOT NULL DEFAULT 5,
    juggling TINYINT UNSIGNED NOT NULL DEFAULT 5,
    shooting TINYINT UNSIGNED NOT NULL DEFAULT 5,
    setplay_position TINYINT UNSIGNED NOT NULL DEFAULT 5,
    passing TINYINT UNSIGNED NOT NULL DEFAULT 5,
    control TINYINT UNSIGNED NOT NULL DEFAULT 5,
    photo VARCHAR(255) NOT NULL DEFAULT '',
    ktp_image VARCHAR(255) NOT NULL DEFAULT '',
    kk_image VARCHAR(255) NOT NULL DEFAULT '',
    birth_cert_image VARCHAR(255) NOT NULL DEFAULT '',
    diploma_image VARCHAR(255) NOT NULL DEFAULT '',
    status ENUM('active', 'inactive') NOT NULL DEFAULT 'inactive',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uq_players_name UNIQUE (name),
    CONSTRAINT uq_players_nik UNIQUE (nik),
    CONSTRAINT fk_players_team FOREIGN KEY (team_id) REFERENCES teams(id)
        ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
